import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [('contacts', '0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(name='BusinessCard', fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)), ('original_file', models.ImageField(upload_to='originals/%Y/%m/%d/')), ('thumbnail_file', models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/%d/')), ('source_type', models.CharField(default='upload', max_length=32)), ('legacy_external_id', models.CharField(blank=True, max_length=255)), ('language_code', models.CharField(blank=True, max_length=32)), ('language_confidence', models.FloatField(blank=True, null=True)), ('xml_raw', models.TextField(blank=True)), ('ocr_raw', models.TextField(blank=True)), ('ocr_confidence', models.FloatField(blank=True, null=True)), ('parsed_text', models.TextField(blank=True)), ('normalized_text', models.TextField(blank=True)), ('transliterated_text', models.TextField(blank=True)), ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('needs_review', 'Needs review'), ('failed', 'Failed')], default='uploaded', max_length=32)), ('needs_manual_review', models.BooleanField(default=True)), ('human_verified', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('contact', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='cards', to='contacts.contact')), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='created_cards', to=settings.AUTH_USER_MODEL)), ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='updated_cards', to=settings.AUTH_USER_MODEL)), ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='verified_cards', to=settings.AUTH_USER_MODEL)), ('verified_at', models.DateTimeField(blank=True, null=True))]),
        migrations.CreateModel(name='ParsedField', fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)), ('target_type', models.CharField(max_length=32)), ('target_id', models.UUIDField()), ('field_name', models.CharField(max_length=100)), ('field_value', models.TextField()), ('field_source', models.CharField(max_length=32)), ('confidence', models.FloatField(blank=True, null=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL))]),
    ]
