import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [('access', '0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(name='Contact', fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)), ('full_name', models.CharField(max_length=255)), ('first_name', models.CharField(max_length=255, blank=True)), ('last_name', models.CharField(max_length=255, blank=True)), ('middle_name', models.CharField(max_length=255, blank=True)), ('company', models.CharField(max_length=255, blank=True)), ('position', models.CharField(max_length=255, blank=True)), ('notes', models.TextField(blank=True)), ('normalized_text', models.TextField(blank=True)), ('transliterated_text', models.TextField(blank=True)), ('search_document', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('access_groups', models.ManyToManyField(blank=True, related_name='contacts', to='access.accessgroup')), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)), ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='updated_contacts', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='ContactAlias', fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)), ('value', models.CharField(max_length=255)), ('source', models.CharField(max_length=16, choices=[('manual', 'Manual'), ('xml', 'XML'), ('ocr', 'OCR'), ('generated', 'Generated')], default='manual')), ('normalized_value', models.CharField(max_length=255, blank=True)), ('transliterated_value', models.CharField(max_length=255, blank=True)), ('contact', models.ForeignKey(on_delete=models.CASCADE, to='contacts.contact'))]),
        migrations.CreateModel(name='ContactPhone', fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)), ('value', models.CharField(max_length=255)), ('source', models.CharField(max_length=16, choices=[('manual', 'Manual'), ('xml', 'XML'), ('ocr', 'OCR'), ('generated', 'Generated')], default='manual')), ('normalized_value', models.CharField(max_length=255, blank=True)), ('transliterated_value', models.CharField(max_length=255, blank=True)), ('contact', models.ForeignKey(on_delete=models.CASCADE, to='contacts.contact'))]),
        migrations.CreateModel(name='ContactEmail', fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)), ('value', models.CharField(max_length=255)), ('source', models.CharField(max_length=16, choices=[('manual', 'Manual'), ('xml', 'XML'), ('ocr', 'OCR'), ('generated', 'Generated')], default='manual')), ('normalized_value', models.CharField(max_length=255, blank=True)), ('transliterated_value', models.CharField(max_length=255, blank=True)), ('contact', models.ForeignKey(on_delete=models.CASCADE, to='contacts.contact'))]),
        migrations.CreateModel(name='ContactWebsite', fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)), ('value', models.CharField(max_length=255)), ('source', models.CharField(max_length=16, choices=[('manual', 'Manual'), ('xml', 'XML'), ('ocr', 'OCR'), ('generated', 'Generated')], default='manual')), ('normalized_value', models.CharField(max_length=255, blank=True)), ('transliterated_value', models.CharField(max_length=255, blank=True)), ('contact', models.ForeignKey(on_delete=models.CASCADE, to='contacts.contact'))]),
        migrations.CreateModel(name='ContactAddress', fields=[('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)), ('value', models.CharField(max_length=255)), ('source', models.CharField(max_length=16, choices=[('manual', 'Manual'), ('xml', 'XML'), ('ocr', 'OCR'), ('generated', 'Generated')], default='manual')), ('normalized_value', models.CharField(max_length=255, blank=True)), ('transliterated_value', models.CharField(max_length=255, blank=True)), ('contact', models.ForeignKey(on_delete=models.CASCADE, to='contacts.contact'))]),
    ]
